services:
  homepage:
    container_name: homepagers
    image: hoffmanju/homepagers:latest
    ports:
      - 8000:8000/tcp
    volumes:
      - ./config.yaml:/site/config.yaml:ro
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: unless-stopped
